language: ruby
cache: bundler
before_script:
  - bin/prepare_ci_repo
  - cp .env-travis .env
  - createdb dry_rb_workshop_blog_test
script:
  - bundle exec rspec
rvm:
  - 2.4.1
notifications:
  email: false
