version: '3.1'
services:
  app:
    build: .
    command: bundle exec shotgun -p 3000 -o 0.0.0.0 config.ru
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "nickel"
      POSTGRES_PASSWORD: "secret"
